name: Build and push to Amazon ECR New

on:
  push:
    branches:
      - wow3-dev
  pull_request:
    branches:
      - wow3-dev

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: 471112935179.dkr.ecr.us-east-1.amazonaws.com/wow3
  REPOSITORY: xmtp-node-go
  AWS_REGION: us-east-1

jobs:
  build_and_push:
    runs-on: wow3-runner
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      - id: meta
        name: Docker Meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,suffix=-{{sha}},event=pr
            type=ref,suffix=-{{sha}},event=tag
            type=semver,event=tag,pattern={{raw}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::471112935179:role/aws-cicd_runner
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          build-args: |
            CACHE_DATE=$(date)
